services:
  - type: web
    plan: free
    name: AmaX
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 -m Anonymous
    repo: https://github.com/AnoxDx/AnonymousUserBot      
    branch: main
    envVars:
      - key: SUDO_USERS 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_URL
        sync: false    
      - key: API_ID
        sync: false  
      - key: API_HASH
        sync: false  
      - key: PM_LOGGER
        sync: false  
      - key: LOG_GROUP
        sync: false  
    autoDeploy: false
